apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: overdraft-manager
  description: Gerenciador de cheque especial #
spec:
  type: service
  lifecycle: production
  owner: group:conta-corrente
  system: system:banking-system
